#!/bin/bash
_fixpoint()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="list lock drop refresh --help"

    if [[ ${cur} == * && ${prev} == fixpoint ]];then
        COMPREPLY=( $(compgen -W "${opts}" ${cur}) )
        return 0
    fi
}
complete -F _fixpoint fixpoint
